<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'tz.exception_listener' shared autowired service.

include_once $this->targetDirs[3].'/src/Bundle/CommunBundle/EventListener/ExceptionListener.php';

return $this->services['tz.exception_listener'] = new \Bundle\CommunBundle\EventListener\ExceptionListener();
