<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'tz.responses' shared service.

include_once $this->targetDirs[3].'/src/Bundle/AdminBundle/Service/FosRestResponse.php';
include_once $this->targetDirs[3].'/src/Bundle/CommunBundle/Service/PreFormatMsg.php';

return $this->services['tz.responses'] = new \Bundle\AdminBundle\Service\FosRestResponse(${($_ = isset($this->services['ws.tz_msg']) ? $this->services['ws.tz_msg'] : $this->services['ws.tz_msg'] = new \Bundle\CommunBundle\Service\PreFormatMsg($this)) && false ?: '_'});
