<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'ws.tz_msg' shared service.

include_once $this->targetDirs[3].'/src/Bundle/CommunBundle/Service/PreFormatMsg.php';

return $this->services['ws.tz_msg'] = new \Bundle\CommunBundle\Service\PreFormatMsg($this);
