<?php

namespace Bundle\UserBundle\Repository;

use Symfony\Component\DependencyInjection\ContainerInterface;

/**
 * CoreRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoreRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * @var
     */
    protected $container;

    /**
     * setContainer.
     *
     * @param ContainerInterface $container
     */
    public function setContainer(ContainerInterface $container = null)
    {
        $this->container = $container;
    }

    /**
     * Executer une requete SQL PLAIN
     *
     * @param string  $sql
     * @param boolean $useCount
     *
     * @return array
     */
    public function __query($sql, $useCount = false)
    {
        $qb = $this->getEntityManager()->getConnection()->prepare($sql);
        $qb->execute();
        if (true === $useCount) {
            $results = $qb->fetchAll(\PDO::FETCH_COLUMN);
            $results = count($results);
        } else {
            $results = $qb->fetchAll();
        }

        return $results;
    }

    /**
     * Géneration offset page
     *
     * @param integer $page
     * @param integer $perPage
     *
     * @return integer
     */
    public function getOffset($page, $perPage)
    {
        $offset = 0;
        if ($page > 1) {
            $offset = (int) ($page - 1) * $perPage;
        }

        return $offset;
    }

    /**
     * Get connexion
     * @return mixed
     */
    public function __getConn()
    {
        return $this->getEntityManager()->getConnection();
    }
}
