export const ConstantFront = {
  but           : "Ity projet ity dia omena ireo sekoly rehetra eto Madagasikara , Natao hahamora ny fiandraiketana ny sekoly,toy ny",
  but1          : "Lisitry ny mpianatra",
  but2          : "Emploi du temps",
  but3          : "Lisitry ny kilasy sy ambaratonga",
  but4          : "Lisitry ny mpampianatra",
  but5          : "Naotin ny mpianatra",
  but6          : "Fandoavana écolage sy karama",
  but7          : "Famandrihana salle",
  but8          : "Lisitry ny mpianatra isakin'ny kilasy",
  soutient      : "Tianao ve ny hanohana anay ?",
  soutient1     : 'Mila sekoly ho atao pilote afaka sady hanaovana teste izahay.',
  soutient2     : 'Mila serveur hi-hebergena ity application ity izahay.',
  soutient3     : "Mila connexion izahay amin'ny traitement retour sy fanatsarana rehetra.",
  soutient4     : "Mila antsika rehetra hanao teste sy handefa retout izahay.",
  soutient5     : "Raha misy remarque dia afaka manao pull request",
  sout1         : "Ato",
  sout2         : "ianao",
  equipe        : "NY EKIPA",
  pre_equipe    : "Ireo ekipa nanatontosa sy miandraikitra ity application ity.",
  Tahiana_dev   : "Developpement api",
  Tahiana_tache : "Tahiana no miandraikitra ny API rehetra ampiasaina ato amin'ity application ity.",
  Antso_front   : "Developpement frontend",
  Antso_tache   : "Ny Antso dia miandraikitra ny integration sy ny developpement frontend.",
  Daulis_front  : "Developpement frontend",
  Daulis_tache  : "Daulis sy Ny Antso dia iray ekipa amin'ny developpement sy dynamisation frontend .",
  Janny_front   : "Intégrateur",
  Janny_tache   : "Janny, miandraikitra ny intégration frontend rehetra miaraka amin'ny Ny Antso sy Daulis.",
  Andry_dev     : "Developpement api",
  Andry_tache   : "Andry no miaraka amin'ny Tahiana amin'ny developpement ny api rehetra ampiasaina ato.",
  Jul_resp      : "Responsable projet",
  Jul_tache     : "Julien no miandraikitra ity projet ity miaraka amin'ny ekipa developpeur sy deployement.",
  sekoliko_vue  : "Ny hitanao ato amin'ity application ity",
  sekoliko_vue1 : "Dashboard",
  dashboard     : "Ahafahanao mijery ny statistique mahakasika ny établissement anao",
  sekoliko_vue2 : "Lisitry ny mpianatra",
  liste_etudiant: "Ahafahanao mijery ny lisitry ny mpianatra rehetra ao amin'ny etablissement misy anao.",
  sekoliko_vue3 : "Lisitry ny salle de classe",
  liste_salle   : "Ahafahanao mijery ny salle libre sy izay efa misy réservation.",
  contributeur  : "Ireo mpiara-miasa aminay",
  google        : "Ato izahay no mianatra sy mijery ny documentation rehetra",
  stackoverflow : "Ato izahay no mitady vahaolana rehefa mirefotra",
  github        : "Ao amin'ny github no misy ny dépot an'ny projet sekoliko",
};
