<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sekoliko_api.jwt_not_found_listener' shared service.

include_once $this->targetDirs[3].'/src/Bundle/CommunBundle/EventListener/JwtListener.php';

return $this->services['sekoliko_api.jwt_not_found_listener'] = new \Bundle\CommunBundle\EventListener\JwtListener();
